In [1]:
import pandas as pd

df = pd.read_parquet('../data/clean_yellow_tripdata_2025-01.parquet')
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,pickup_hour,pickup_date,weekday,is_weekend,trip_duration_min,trip_speed_mph,tip_pct,long_trip,high_tip,revenue_per_mile
0,1,2025-01-01 02:32:52,2025-01-01 02:33:53,3.0,6.10,5.0,N,48,48,1,...,2,2025-01-01,2,False,1.016667,80.0,16.666667,False,False,6.098361
1,2,2025-01-01 10:52:25,2025-01-01 11:08:19,1.0,47.05,1.0,N,265,138,1,...,10,2025-01-01,2,False,15.900000,80.0,16.666667,True,False,0.938576
2,2,2025-01-02 18:50:41,2025-01-02 18:55:51,1.0,18.15,1.0,N,161,233,1,...,18,2025-01-02,3,False,5.166667,80.0,16.666667,True,False,1.236364
3,1,2025-01-03 12:27:01,2025-01-03 12:28:26,1.0,15.50,5.0,N,146,146,1,...,12,2025-01-03,4,False,1.416667,80.0,6.993007,True,False,4.612903
4,1,2025-01-03 12:40:59,2025-01-03 12:42:10,0.0,2.30,1.0,N,100,100,2,...,12,2025-01-03,4,False,1.183333,80.0,0.000000,False,False,3.043478

In [6]:
MIN_TRIPS = 3

In [4]:
pd.DataFrame([overall_kpis]).to_csv('../data/business_overview_kpis.csv', index=False)

In [7]:
zone_summary = df.groupby('PULocationID').agg(
    avg_distance=('trip_distance','mean'),
    avg_revenue=('total_amount','mean'),
    num_trips=('trip_distance','count')
).reset_index()

robust_long_zones = (
    zone_summary[zone_summary['num_trips'] >= MIN_TRIPS]
    .sort_values('avg_distance', ascending=False)
)

robust_long_zones.head(10)

    PULocationID  avg_distance  avg_revenue  num_trips
63           265     31.240000   104.676667          3
7             42     21.573333    16.973333          3
30           140     19.500000    25.486667          3
32           142     19.000000    14.402500          4
27           132     17.900000    81.522000          5
54           238     17.866667    20.206667          3
52           236     17.200000    12.413333          3
35           145     17.100000     6.180000          5
48           230     17.007500    21.815000          4
50           232     15.960000    14.323333          3

In [9]:
vendor_summary = df.groupby('VendorID').agg(
    avg_revenue=('total_amount','mean'),
    avg_distance=('trip_distance','mean'),
    avg_tip_pct=('tip_pct','mean'),
    num_trips=('trip_distance','count')
).reset_index()

vendor_summary

   VendorID  avg_revenue  avg_distance  avg_tip_pct  num_trips
0         1    21.858977     20.607955     1.498620         88
1         2    32.980870     20.443043     8.079765         23

In [10]:
correlation = df[['trip_distance','tip_pct']].corr()
correlation

               trip_distance   tip_pct
trip_distance       1.000000 -0.128291
tip_pct            -0.128291  1.000000

In [12]:
df[['trip_distance','tip_amount']].corr()

               trip_distance  tip_amount
trip_distance       1.000000   -0.094951
tip_amount         -0.094951    1.000000